// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.3
// source: config/pbconfig/bostsetup.proto

package bpconfig

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string       `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ListenOn   string       `protobuf:"bytes,2,opt,name=ListenOn,proto3" json:"ListenOn,omitempty"`
	Timeout    int64        `protobuf:"varint,3,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	Etcd       *Etcd        `protobuf:"bytes,4,opt,name=Etcd,proto3" json:"Etcd,omitempty"`
	Mysql      *Mysql       `protobuf:"bytes,5,opt,name=Mysql,proto3" json:"Mysql,omitempty"`
	CacheRedis []*RedisConf `protobuf:"bytes,6,rep,name=CacheRedis,proto3" json:"CacheRedis,omitempty"`
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_pbconfig_bostsetup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_config_pbconfig_bostsetup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_config_pbconfig_bostsetup_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bootstrap) GetListenOn() string {
	if x != nil {
		return x.ListenOn
	}
	return ""
}

func (x *Bootstrap) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Bootstrap) GetEtcd() *Etcd {
	if x != nil {
		return x.Etcd
	}
	return nil
}

func (x *Bootstrap) GetMysql() *Mysql {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *Bootstrap) GetCacheRedis() []*RedisConf {
	if x != nil {
		return x.CacheRedis
	}
	return nil
}

type Etcd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosts []string `protobuf:"bytes,1,rep,name=Hosts,proto3" json:"Hosts,omitempty"`
	Key   string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (x *Etcd) Reset() {
	*x = Etcd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_pbconfig_bostsetup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Etcd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Etcd) ProtoMessage() {}

func (x *Etcd) ProtoReflect() protoreflect.Message {
	mi := &file_config_pbconfig_bostsetup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Etcd.ProtoReflect.Descriptor instead.
func (*Etcd) Descriptor() ([]byte, []int) {
	return file_config_pbconfig_bostsetup_proto_rawDescGZIP(), []int{1}
}

func (x *Etcd) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *Etcd) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Mysql struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataSource string `protobuf:"bytes,1,opt,name=DataSource,proto3" json:"DataSource,omitempty"`
}

func (x *Mysql) Reset() {
	*x = Mysql{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_pbconfig_bostsetup_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mysql) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mysql) ProtoMessage() {}

func (x *Mysql) ProtoReflect() protoreflect.Message {
	mi := &file_config_pbconfig_bostsetup_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mysql.ProtoReflect.Descriptor instead.
func (*Mysql) Descriptor() ([]byte, []int) {
	return file_config_pbconfig_bostsetup_proto_rawDescGZIP(), []int{2}
}

func (x *Mysql) GetDataSource() string {
	if x != nil {
		return x.DataSource
	}
	return ""
}

type RedisConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string                 `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	Pass string                 `protobuf:"bytes,2,opt,name=Pass,proto3" json:"Pass,omitempty"`
	Type string                 `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	DB   *wrapperspb.Int32Value `protobuf:"bytes,4,opt,name=DB,proto3" json:"DB,omitempty"`
}

func (x *RedisConf) Reset() {
	*x = RedisConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_pbconfig_bostsetup_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedisConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisConf) ProtoMessage() {}

func (x *RedisConf) ProtoReflect() protoreflect.Message {
	mi := &file_config_pbconfig_bostsetup_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisConf.ProtoReflect.Descriptor instead.
func (*RedisConf) Descriptor() ([]byte, []int) {
	return file_config_pbconfig_bostsetup_proto_rawDescGZIP(), []int{3}
}

func (x *RedisConf) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RedisConf) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

func (x *RedisConf) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RedisConf) GetDB() *wrapperspb.Int32Value {
	if x != nil {
		return x.DB
	}
	return nil
}

var File_config_pbconfig_bostsetup_proto protoreflect.FileDescriptor

var file_config_pbconfig_bostsetup_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x70, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2f, 0x62, 0x6f, 0x73, 0x74, 0x73, 0x65, 0x74, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x70, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x1e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd5, 0x01, 0x0a, 0x09,
	0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x4f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x4f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x45, 0x74, 0x63, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x45, 0x74, 0x63,
	0x64, 0x52, 0x04, 0x45, 0x74, 0x63, 0x64, 0x12, 0x25, 0x0a, 0x05, 0x4d, 0x79, 0x73, 0x71, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x52, 0x05, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x12, 0x33,
	0x0a, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x64, 0x69, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65,
	0x64, 0x69, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65,
	0x64, 0x69, 0x73, 0x22, 0x2e, 0x0a, 0x04, 0x45, 0x74, 0x63, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x48,
	0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x48, 0x6f, 0x73, 0x74,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4b, 0x65, 0x79, 0x22, 0x27, 0x0a, 0x05, 0x4d, 0x79, 0x73, 0x71, 0x6c, 0x12, 0x1e, 0x0a, 0x0a,
	0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x74, 0x0a, 0x09,
	0x52, 0x65, 0x64, 0x69, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x73,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x02, 0x44, 0x42, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x02,
	0x44, 0x42, 0x42, 0x2a, 0x5a, 0x28, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x5f, 0x6c, 0x65, 0x61,
	0x72, 0x6e, 0x2f, 0x42, 0x50, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x62, 0x70, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x3b, 0x62, 0x70, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_pbconfig_bostsetup_proto_rawDescOnce sync.Once
	file_config_pbconfig_bostsetup_proto_rawDescData = file_config_pbconfig_bostsetup_proto_rawDesc
)

func file_config_pbconfig_bostsetup_proto_rawDescGZIP() []byte {
	file_config_pbconfig_bostsetup_proto_rawDescOnce.Do(func() {
		file_config_pbconfig_bostsetup_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_pbconfig_bostsetup_proto_rawDescData)
	})
	return file_config_pbconfig_bostsetup_proto_rawDescData
}

var file_config_pbconfig_bostsetup_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_config_pbconfig_bostsetup_proto_goTypes = []interface{}{
	(*Bootstrap)(nil),             // 0: pbconfig.Bootstrap
	(*Etcd)(nil),                  // 1: pbconfig.Etcd
	(*Mysql)(nil),                 // 2: pbconfig.Mysql
	(*RedisConf)(nil),             // 3: pbconfig.RedisConf
	(*wrapperspb.Int32Value)(nil), // 4: google.protobuf.Int32Value
}
var file_config_pbconfig_bostsetup_proto_depIdxs = []int32{
	1, // 0: pbconfig.Bootstrap.Etcd:type_name -> pbconfig.Etcd
	2, // 1: pbconfig.Bootstrap.Mysql:type_name -> pbconfig.Mysql
	3, // 2: pbconfig.Bootstrap.CacheRedis:type_name -> pbconfig.RedisConf
	4, // 3: pbconfig.RedisConf.DB:type_name -> google.protobuf.Int32Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_config_pbconfig_bostsetup_proto_init() }
func file_config_pbconfig_bostsetup_proto_init() {
	if File_config_pbconfig_bostsetup_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_pbconfig_bostsetup_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bootstrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_pbconfig_bostsetup_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Etcd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_pbconfig_bostsetup_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mysql); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_pbconfig_bostsetup_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedisConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_pbconfig_bostsetup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_pbconfig_bostsetup_proto_goTypes,
		DependencyIndexes: file_config_pbconfig_bostsetup_proto_depIdxs,
		MessageInfos:      file_config_pbconfig_bostsetup_proto_msgTypes,
	}.Build()
	File_config_pbconfig_bostsetup_proto = out.File
	file_config_pbconfig_bostsetup_proto_rawDesc = nil
	file_config_pbconfig_bostsetup_proto_goTypes = nil
	file_config_pbconfig_bostsetup_proto_depIdxs = nil
}
