Name: gw.rpc
ListenOn: gwrpc:8080
Timeout: 0

Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: gw.rpc

Mysql:
  DataSource: root:root@tcp(127.0.0.1:3306)/gwstore_dev?charset=utf8&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: 127.0.0.1
    Pass: "123456"
    Type: node
    DB: 2